#include "runtime/purescript.h"

PURS_FFI_VALUE(Main_a$, PURS_ANY_NUMBER(0.0));
PURS_FFI_VALUE(Main_b$, PURS_ANY_NUMBER(1.0));
PURS_FFI_VALUE(Main_c$, PURS_ANY_NUMBER(2.0));
PURS_FFI_VALUE(Main_d$, PURS_ANY_NUMBER(3.0));
